ENH: Added `CARDReadsKmerAnalysis` and `CARDMAGsKmerAnalysis` types
bokulich-lab/q2-amr pull request #48
Opened 2024-02-09 17:24 UTC by VinzentRisch

This PR closes #47

- Added `CARDReadsKmerAnalysis` and `CARDMAGsKmerAnalysis` types.
- The two actions that will be added described in #21 will output these types.

### Set up an environment
```bash
CONDA_SUBDIR=osx-64 mamba create -yn q2-amr \
  -c conda-forge -c bioconda -c qiime2 -c defaults \
  -c https://packages.qiime2.org/qiime2/2023.9/shotgun/released/ \
  qiime2 q2cli q2templates q2-types q2-types-genomics rgi rnanorm

conda activate q2-amr
conda config --env --set subdir osx-64

pip install --no-deps --force-reinstall \
  git+https://github.com/misialq/rgi.git@py38-fix \
```

### Run it locally 
1. First, clone the repo and checkout the PR branch:
```bash
git clone https://github.com/bokulich-lab/q2-amr.git
cd q2-amr
git fetch origin pull/48/head:pr-48
git checkout pr-48
pip install -e .
```
2. Download test files 
[Download test files](https://polybox.ethz.ch/index.php/s/nJmbGpkM1ywS9VW): 

3. Test it out!
```bash
qiime tools import --input-path  --output-path  --type CARDReadsKmerAnalysis
qiime tools import --input-path  --output-path  --type CARDMAGsKmerAnalysis
 ```

2024-02-28 14:53 UTC, VinzentRisch commented
Hi @ChristosMatzoros 
Can you look this over? its really small just a couple of types.

2024-03-07 09:49 UTC, ChristosMatzoros requested changes

2024-03-07 09:49 UTC, ChristosMatzoros commented on q2_amr/types/_format.py
> +        if keys_obs != keys_exp:
If you don't want a specific order to the columns, consider using a set comparison to ensure that all expected keys are present without enforcing the order. For example, use `set(keys_obs) != set(keys_exp)`

2024-03-07 09:49 UTC, ChristosMatzoros commented on q2_amr/types/_format.py
> +        if keys_obs != keys_exp:
Same as my previous comment, change to comparing sets if you don't care about enforcing order to the columns.

2024-03-14 10:05 UTC, ChristosMatzoros approved these changes
Hey @VinzentRisch , everything works as expected. You can merge!

2024-03-14 10:32 UTC, merged