ENH: Added sample_dict to `CARDAlleleAnnotationDirectoryFormat` , `CARDGeneAnnotationDirectoryFormat` and `CARDAnnotationDirectoryFormat`
bokulich-lab/q2-amr pull request #59
Opened 2024-03-21 16:11 UTC by VinzentRisch

- Added sample_dict function to `CARDAlleleAnnotationDirectoryFormat` , `CARDGeneAnnotationDirectoryFormat` and `CARDAnnotationDirectoryFormat`
- This function returns a dict where keys are sample names and values are paths to the annotation files.

2024-03-22 07:06 UTC, misialq requested changes
Hey @VinzentRisch, looks good! See some small suggestions below, otherwise seems alright 😄

2024-03-22 07:06 UTC, misialq commented on q2_amr/types/_format.py
> +            file = list(os.path.join(sample, "gene_mapping_data.txt"))
Let's not introduce variables where not necessary - you can also just assign the value directly below.

2024-03-22 07:06 UTC, misialq commented on q2_amr/types/tests/test_types_formats_transformers.py
> +                ]
I love this loop obsession 😵‍💫

2024-03-22 07:06 UTC, misialq commented on q2_amr/types/tests/test_types_formats_transformers.py
> +            "sample2": list(os.path.join(dirpath, "sample2", "gene_mapping_data.txt")),
```suggestion
            "sample1": [os.path.join(dirpath, "sample1", "gene_mapping_data.txt"),],
            "sample2": [os.path.join(dirpath, "sample2", "gene_mapping_data.txt"),],
```

2024-03-22 08:41 UTC, VinzentRisch commented
Hi @misialq  
Sorry for all the loops, will avoid this in the future :)

2024-03-25 15:02 UTC, misialq approved these changes
Awesome, thanks @VinzentRisch! Feel free to merge whenever ready :)

2024-03-26 13:12 UTC, merged