ENH: Added feature table output to annotate-mags-card
bokulich-lab/q2-amr pull request #8
Opened 2023-07-12 15:06 UTC by VinzentRisch

2023-10-03 11:48 UTC, misialq requested changes
OK, I had another look and left some inline comments for you to check out. After that, I think we should just merge it as-is. I'll go through it after that once again, try it out in practice and maybe just create some issues for you to work on in case there are more changes needed. How does that sound?

2023-10-03 11:48 UTC, misialq commented on q2_amr/types/_transformer.py
> +    annotation_dir = data
Can you maybe rather just rename the `data` argument to be the `annotation_dir` and remove this line?

2023-10-03 11:48 UTC, misialq commented on q2_amr/types/_transformer.py
> +def tabulate_data(data_path, data):
Can you change `data` to something like `data_type`? It's not really obvious what "data" should contain otherwise...

2023-10-03 11:48 UTC, misialq commented on q2_amr/types/_transformer.py
> +        df = pd.read_csv(file_path, sep="\t")
This is a bit strange - so after the if-else statement, in I provided "mags" (first branch), there would be a bunch of dataframes read in but now you would read the last one in _again_ - maybe I'm missing something but this does not seem correct...

2023-10-03 11:48 UTC, misialq commented on q2_amr/types/_transformer.py
> +    metadata = qiime2.Metadata(df_combined)
You can also just directly return `qiime2.Metadata(df_combined)` since you're not really using that variable for anything.

2023-10-06 11:16 UTC, closed without merging

2023-10-06 11:16 UTC, VinzentRisch commented
will be reopened